/*
DB pre-check script for V1-SendNotification
Purpose:
1) Verify required tables/columns exist
2) Verify config values are in expected ranges
3) Show invalid/nullable risky values

Run on SQL Server in target institution DB.
If your schema is not dbo, change @SchemaName.
*/

SET NOCOUNT ON;

DECLARE @SchemaName SYSNAME = 'dbo';

PRINT '=== STEP 1: Required tables ===';

DECLARE @RequiredTables TABLE (TableName SYSNAME);
INSERT INTO @RequiredTables (TableName)
VALUES
('K_DAHIKOD_AYARLAR'),
('S_GENELAYARLAR'),
('K_DAHIKOD_BILDIRIM'),
('K_DAHIKOD_CAGRI');

SELECT
    t.TableName,
    CASE WHEN OBJECT_ID(QUOTENAME(@SchemaName) + '.' + QUOTENAME(t.TableName), 'U') IS NULL THEN 'MISSING' ELSE 'OK' END AS TableStatus
FROM @RequiredTables t
ORDER BY t.TableName;

PRINT '=== STEP 2: Required columns ===';

DECLARE @RequiredColumns TABLE (
    TableName SYSNAME,
    ColumnName SYSNAME,
    ExpectedType VARCHAR(100),
    ExpectedValues VARCHAR(200)
);

/* K_DAHIKOD_AYARLAR */
INSERT INTO @RequiredColumns VALUES
('K_DAHIKOD_AYARLAR','BILDIRIM_GONDERME_DENEME_SAYISI','INT','> 0'),
('K_DAHIKOD_AYARLAR','KAC_DAKIKA_ONCEKI_BILDIRIM_GONDERILSIN','INT','> 0'),
('K_DAHIKOD_AYARLAR','NET_GSM_BIRINCI_FIRMA','BIT/INT','0 or 1'),
('K_DAHIKOD_AYARLAR','TEK_SEFERDE_SMS_GONDERILECEK_KISI_SAYISI','INT','> 0'),
('K_DAHIKOD_AYARLAR','TEK_SEFERDE_SESLI_CAGRI_GONDERILECEK_KISI_SAYISI','INT','> 0'),
('K_DAHIKOD_AYARLAR','TEK_SEFERDE_MAIL_GONDERILECEK_KISI_SAYISI','INT','> 0'),
('K_DAHIKOD_AYARLAR','KOBICOM_BIRINCI_FIRMA','BIT/INT','0 or 1'),
('K_DAHIKOD_AYARLAR','KIRMIZI_SANTRAL_BIRINCI_FIRMA','BIT/INT','0 or 1'),
('K_DAHIKOD_AYARLAR','AKTIF_BIRINCI_FIRMA','VARCHAR','NETGSM|KIRMIZISANTRAL|KOBIKOM'),
('K_DAHIKOD_AYARLAR','AKTIF_IKINCI_FIRMA','VARCHAR','NETGSM|KIRMIZISANTRAL|KOBIKOM'),
('K_DAHIKOD_AYARLAR','CAGRI_SONLANDIRMA_GERI_ARAMASI','BIT/INT','0 or 1'),
('K_DAHIKOD_AYARLAR','CAGRI_SONLANDIRMA_ARAMA_BASLAMA_DAKIKASI','INT','>= 0'),
('K_DAHIKOD_AYARLAR','CAGRI_SONLANDIRMA_ARAMA_BITIS_DAKIKASI','INT','>= 0');

/* S_GENELAYARLAR */
INSERT INTO @RequiredColumns VALUES
('S_GENELAYARLAR','SMS_DURUM','BIT/INT','0 or 1'),
('S_GENELAYARLAR','EPOSTA_DURUM','BIT/INT','0 or 1'),
('S_GENELAYARLAR','SESLI_CAGRI_AKTIF','BIT/INT','0 or 1');

/* K_DAHIKOD_BILDIRIM (runtime critical) */
INSERT INTO @RequiredColumns VALUES
('K_DAHIKOD_BILDIRIM','BILDIRIM_DENEME_ID','INT','PK/unique recommended'),
('K_DAHIKOD_BILDIRIM','CAGRI_ID','INT','FK to K_DAHIKOD_CAGRI.CAGRI_ID'),
('K_DAHIKOD_BILDIRIM','PERSONEL_TELEFON','VARCHAR','phone text'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_OLUSTURMA_ZAMANI','DATETIME','not null recommended'),
('K_DAHIKOD_BILDIRIM','KAYIT_KONTROL_EDILDI','BIT/INT','0 or 1'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_SMS','BIT/INT','0 or 1'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_METNI','VARCHAR','sms text'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_SMS_ISLEM_ACIKLAMA','VARCHAR','Beklemede|Gonderilemedi|...'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_SESLI_CAGRI','BIT/INT','0 or 1'),
('K_DAHIKOD_BILDIRIM','SESLI_CAGRI_METNI','VARCHAR','voice text'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_SESLI_CAGRI_ISLEM_ACIKLAMA','VARCHAR','Beklemede|Gonderilemedi|...'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_SESLI_CAGRI_DURUM','BIT/INT','0 or 1'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_MOBILE','BIT/INT','0 or 1'),
('K_DAHIKOD_BILDIRIM','BILDIRIM_MOBILE_ISLEM_ACIKLAMA','VARCHAR','Beklemede|...'),
('K_DAHIKOD_BILDIRIM','CAGRI_ONAYI_HATIRLARMA_ARAMA_SAYISI','INT','>= 0'),
('K_DAHIKOD_BILDIRIM','CAGRI_ONAYI_HATIRLATMA_ARAMASI_YAPILACAK','BIT/INT','0 or 1'),
('K_DAHIKOD_BILDIRIM','CAGRI_ONAY_BILDIRIM_METNI','VARCHAR','not null for reminder records');

/* K_DAHIKOD_CAGRI (runtime critical) */
INSERT INTO @RequiredColumns VALUES
('K_DAHIKOD_CAGRI','CAGRI_ID','INT','PK/unique recommended'),
('K_DAHIKOD_CAGRI','CAGRI_DURUMU','INT','1 used in reminder flow'),
('K_DAHIKOD_CAGRI','CAGRI_ZAMANI','DATETIME','not null recommended'),
('K_DAHIKOD_CAGRI','TEST_CAGRISI','BIT/INT','0 for real calls');

SELECT
    rc.TableName,
    rc.ColumnName,
    rc.ExpectedType,
    rc.ExpectedValues,
    CASE WHEN c.column_id IS NULL THEN 'MISSING' ELSE 'OK' END AS ColumnStatus,
    t.name AS ActualType,
    c.max_length,
    c.is_nullable
FROM @RequiredColumns rc
LEFT JOIN sys.tables st
    ON st.name = rc.TableName
LEFT JOIN sys.schemas ss
    ON ss.schema_id = st.schema_id
    AND ss.name = @SchemaName
LEFT JOIN sys.columns c
    ON c.object_id = st.object_id
    AND c.name = rc.ColumnName
LEFT JOIN sys.types t
    ON t.user_type_id = c.user_type_id
ORDER BY rc.TableName, rc.ColumnName;

PRINT '=== STEP 3: Value checks (K_DAHIKOD_AYARLAR) ===';

IF OBJECT_ID(QUOTENAME(@SchemaName) + '.[K_DAHIKOD_AYARLAR]', 'U') IS NOT NULL
BEGIN
    SELECT TOP 1 *
    FROM K_DAHIKOD_AYARLAR;

    SELECT
        CASE WHEN BILDIRIM_GONDERME_DENEME_SAYISI IS NULL OR BILDIRIM_GONDERME_DENEME_SAYISI <= 0 THEN 'INVALID' ELSE 'OK' END AS BILDIRIM_GONDERME_DENEME_SAYISI,
        CASE WHEN KAC_DAKIKA_ONCEKI_BILDIRIM_GONDERILSIN IS NULL OR KAC_DAKIKA_ONCEKI_BILDIRIM_GONDERILSIN <= 0 THEN 'INVALID' ELSE 'OK' END AS KAC_DAKIKA_ONCEKI_BILDIRIM_GONDERILSIN,
        CASE WHEN TEK_SEFERDE_SMS_GONDERILECEK_KISI_SAYISI IS NULL OR TEK_SEFERDE_SMS_GONDERILECEK_KISI_SAYISI <= 0 THEN 'INVALID' ELSE 'OK' END AS TEK_SEFERDE_SMS_GONDERILECEK_KISI_SAYISI,
        CASE WHEN TEK_SEFERDE_SESLI_CAGRI_GONDERILECEK_KISI_SAYISI IS NULL OR TEK_SEFERDE_SESLI_CAGRI_GONDERILECEK_KISI_SAYISI <= 0 THEN 'INVALID' ELSE 'OK' END AS TEK_SEFERDE_SESLI_CAGRI_GONDERILECEK_KISI_SAYISI,
        CASE WHEN TEK_SEFERDE_MAIL_GONDERILECEK_KISI_SAYISI IS NULL OR TEK_SEFERDE_MAIL_GONDERILECEK_KISI_SAYISI <= 0 THEN 'INVALID' ELSE 'OK' END AS TEK_SEFERDE_MAIL_GONDERILECEK_KISI_SAYISI,
        CASE WHEN NET_GSM_BIRINCI_FIRMA NOT IN (0,1) THEN 'INVALID' ELSE 'OK' END AS NET_GSM_BIRINCI_FIRMA,
        CASE WHEN KOBICOM_BIRINCI_FIRMA NOT IN (0,1) THEN 'INVALID' ELSE 'OK' END AS KOBICOM_BIRINCI_FIRMA,
        CASE WHEN KIRMIZI_SANTRAL_BIRINCI_FIRMA NOT IN (0,1) THEN 'INVALID' ELSE 'OK' END AS KIRMIZI_SANTRAL_BIRINCI_FIRMA,
        CASE WHEN CAGRI_SONLANDIRMA_GERI_ARAMASI NOT IN (0,1) THEN 'INVALID' ELSE 'OK' END AS CAGRI_SONLANDIRMA_GERI_ARAMASI,
        CASE WHEN CAGRI_SONLANDIRMA_ARAMA_BASLAMA_DAKIKASI IS NULL OR CAGRI_SONLANDIRMA_ARAMA_BASLAMA_DAKIKASI < 0 THEN 'INVALID' ELSE 'OK' END AS CAGRI_SONLANDIRMA_ARAMA_BASLAMA_DAKIKASI,
        CASE WHEN CAGRI_SONLANDIRMA_ARAMA_BITIS_DAKIKASI IS NULL OR CAGRI_SONLANDIRMA_ARAMA_BITIS_DAKIKASI < 0 THEN 'INVALID' ELSE 'OK' END AS CAGRI_SONLANDIRMA_ARAMA_BITIS_DAKIKASI,
        CASE WHEN UPPER(ISNULL(AKTIF_BIRINCI_FIRMA,'')) NOT IN ('NETGSM','KIRMIZISANTRAL','KOBIKOM') THEN 'INVALID' ELSE 'OK' END AS AKTIF_BIRINCI_FIRMA,
        CASE WHEN UPPER(ISNULL(AKTIF_IKINCI_FIRMA,'')) NOT IN ('NETGSM','KIRMIZISANTRAL','KOBIKOM') THEN 'INVALID' ELSE 'OK' END AS AKTIF_IKINCI_FIRMA,
        CASE WHEN UPPER(ISNULL(AKTIF_BIRINCI_FIRMA,'')) = UPPER(ISNULL(AKTIF_IKINCI_FIRMA,'')) THEN 'INVALID_SAME_FIRMA' ELSE 'OK' END AS AKTIF_FIRMA_COMBINATION
    FROM K_DAHIKOD_AYARLAR;
END
ELSE
BEGIN
    PRINT 'K_DAHIKOD_AYARLAR table is missing; value checks skipped.';
END;

PRINT '=== STEP 4: Value checks (S_GENELAYARLAR) ===';

IF OBJECT_ID(QUOTENAME(@SchemaName) + '.[S_GENELAYARLAR]', 'U') IS NOT NULL
BEGIN
    SELECT TOP 1 *
    FROM S_GENELAYARLAR;

    SELECT
        CASE WHEN SMS_DURUM NOT IN (0,1) THEN 'INVALID' ELSE 'OK' END AS SMS_DURUM,
        CASE WHEN EPOSTA_DURUM NOT IN (0,1) THEN 'INVALID' ELSE 'OK' END AS EPOSTA_DURUM,
        CASE WHEN SESLI_CAGRI_AKTIF NOT IN (0,1) THEN 'INVALID' ELSE 'OK' END AS SESLI_CAGRI_AKTIF
    FROM S_GENELAYARLAR;
END
ELSE
BEGIN
    PRINT 'S_GENELAYARLAR table is missing; value checks skipped.';
END;

PRINT '=== STEP 5: Runtime data sanity (optional) ===';

IF OBJECT_ID(QUOTENAME(@SchemaName) + '.[K_DAHIKOD_BILDIRIM]', 'U') IS NOT NULL
BEGIN
    SELECT
        SUM(CASE WHEN BILDIRIM_OLUSTURMA_ZAMANI IS NULL THEN 1 ELSE 0 END) AS Null_BILDIRIM_OLUSTURMA_ZAMANI,
        SUM(CASE WHEN KAYIT_KONTROL_EDILDI NOT IN (0,1) THEN 1 ELSE 0 END) AS Invalid_KAYIT_KONTROL_EDILDI,
        SUM(CASE WHEN BILDIRIM_SMS NOT IN (0,1) THEN 1 ELSE 0 END) AS Invalid_BILDIRIM_SMS,
        SUM(CASE WHEN BILDIRIM_SESLI_CAGRI NOT IN (0,1) THEN 1 ELSE 0 END) AS Invalid_BILDIRIM_SESLI_CAGRI,
        SUM(CASE WHEN BILDIRIM_MOBILE NOT IN (0,1) THEN 1 ELSE 0 END) AS Invalid_BILDIRIM_MOBILE,
        SUM(CASE WHEN BILDIRIM_SESLI_CAGRI_DURUM NOT IN (0,1) THEN 1 ELSE 0 END) AS Invalid_BILDIRIM_SESLI_CAGRI_DURUM
    FROM K_DAHIKOD_BILDIRIM;
END;

PRINT '=== DONE ===';
PRINT 'If any MISSING/INVALID appears, fix DB schema/data before deployment.';
